const products=[
{id:1,name:'Air Court Sand',audience:'men',price:24900,img:'assets/casual-beige.jpg',tag:'BEST SELLER',status:'best',desc:'Premium neutral court sneaker with layered suede panels.'},
{id:2,name:'Urban Balance Beige',audience:'women',price:23500,img:'assets/urban-beige.jpg',tag:'NEW',status:'new',desc:'Minimal everyday sneaker with soft neutral styling.'},
{id:3,name:'Flex Knit Crimson',audience:'men',price:27900,img:'assets/flex-red.jpg',tag:'TRENDING',status:'trending',desc:'Lightweight knit runner with flexible all-day cushioning.'},
{id:4,name:'Zoom Pulse Volt',audience:'women',price:29900,img:'assets/zoom-lime.jpg',tag:'BEST SELLER',status:'best',desc:'Sculpted performance silhouette in a high-energy colorway.'},
{id:5,name:'Cloud Runner White',audience:'women',price:26900,img:'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/casual-beige.jpg',tag:'NEW',status:'new',desc:'Crisp white running profile designed for daily movement.'},
{id:6,name:'Retro Street Low',audience:'men',price:25900,img:'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/flex-red.jpg',tag:'TRENDING',status:'trending',desc:'Retro-inspired low top with modern street proportions.'},
{id:7,name:'Studio Runner Rose',audience:'women',price:28900,img:'https://images.pexels.com/photos/1456706/pexels-photo-1456706.jpeg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/zoom-lime.jpg',tag:'NEW',status:'new',desc:'Soft tonal runner made for athleisure and everyday wear.'},
{id:8,name:'Metro High Black',audience:'men',price:31900,img:'https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/flex-red.jpg',tag:'BEST SELLER',status:'best',desc:'High-top street sneaker with a bold monochrome finish.'},
{id:9,name:'Classic Canvas White',audience:'women',price:19900,img:'https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/urban-beige.jpg',tag:'TRENDING',status:'trending',desc:'Timeless canvas low top with clean everyday versatility.'},
{id:10,name:'Leather Street One',audience:'men',price:33900,img:'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/casual-beige.jpg',tag:'NEW',status:'new',desc:'Premium leather profile with a streamlined casual sole.'},
{id:11,name:'Motion Knit Grey',audience:'women',price:27400,img:'https://images.pexels.com/photos/1240892/pexels-photo-1240892.jpeg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/zoom-lime.jpg',tag:'BEST SELLER',status:'best',desc:'Breathable knit upper with responsive underfoot comfort.'},
{id:12,name:'Trail Core Earth',audience:'men',price:34900,img:'https://images.pexels.com/photos/1464625/pexels-photo-1464625.jpeg?auto=compress&cs=tinysrgb&w=1200',fallback:'assets/urban-beige.jpg',tag:'TRENDING',status:'trending',desc:'Rugged mixed-material runner for city and trail styling.'}
];
const $=s=>document.querySelector(s),money=n=>'PKR '+n.toLocaleString();let cart=[],active=null;
function card(p){return `<article class="product-card"><div class="product-media"><span class="badge ${p.status}">${p.tag}</span><img src="${p.img}" data-fallback="${p.fallback||p.img}" alt="${p.name}" loading="lazy"><button class="quick" data-view="${p.id}" aria-label="View ${p.name}">↗</button></div><div class="product-body"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button data-add="${p.id}">Add to bag</button></div></div></article>`}
function render(sel,list){$(sel).innerHTML=list.map(card).join('');$(sel).querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{if(img.src!==img.dataset.fallback)img.src=img.dataset.fallback},{once:true}))}
render('#newProducts',products.filter(p=>p.status==='new').slice(0,5));render('#collectionProducts',products);
$('#filters').addEventListener('click',e=>{let f=e.target.dataset.filter;if(!f)return;$('#filters').querySelectorAll('button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');let list=f==='all'?products:f==='new'?products.filter(p=>p.status==='new'):f==='best'?products.filter(p=>p.status==='best'):products.filter(p=>p.audience===f);render('#collectionProducts',list)});
document.querySelectorAll('.filter-link').forEach(a=>a.addEventListener('click',()=>setTimeout(()=>document.querySelector(`[data-filter="${a.dataset.target}"]`).click(),350)));
const hero=$('.hero-scroll'),video=$('#heroVideo'),progress=$('#progress');let target=0,current=0,seekPending=false;video.addEventListener('loadedmetadata',()=>{video.pause();video.currentTime=.02});addEventListener('scroll',()=>{const r=hero.getBoundingClientRect(),range=Math.max(1,hero.offsetHeight-innerHeight);target=Math.max(0,Math.min(1,-r.top/range));progress.style.height=target*100+'%'},{passive:true});function videoLoop(){current+=(target-current)*.34;if(video.duration&&!seekPending){const t=current*(video.duration-.025);if(Math.abs(video.currentTime-t)>.018){seekPending=true;video.currentTime=t}}requestAnimationFrame(videoLoop)}video.addEventListener('seeked',()=>seekPending=false);requestAnimationFrame(videoLoop);
const canvas=$('#waterCanvas'),ctx=canvas.getContext('2d');function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize);function water(t){ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=0;i<7;i++){ctx.beginPath();let y=innerHeight*(.62+i*.052);for(let x=0;x<=innerWidth;x+=18){let wave=Math.sin(x*.009+t*.0016+i)*10+Math.sin(x*.003-t*.001+i)*7;x?ctx.lineTo(x,y+wave):ctx.moveTo(x,y+wave)}ctx.strokeStyle=`rgba(255,255,255,${.12-i*.01})`;ctx.lineWidth=1.2;ctx.stroke()}requestAnimationFrame(water)}requestAnimationFrame(water);
let drag=false,lastX=0,auto=true;const stage=$('#shoeStage'),stageVideo=$('#stageShoe'),videoShell=stage.querySelector('.video-shell');stage.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;stage.classList.add('dragging');stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag||!stageVideo.duration)return;const delta=e.clientX-lastX;lastX=e.clientX;stageVideo.currentTime=(stageVideo.currentTime+delta*.008+stageVideo.duration)%stageVideo.duration;videoShell.style.setProperty('--drag-tilt',Math.max(-9,Math.min(9,delta*.35))+'deg')});function endStageDrag(){drag=false;stage.classList.remove('dragging');videoShell.style.setProperty('--drag-tilt','0deg');if(auto)stageVideo.play().catch(()=>{})}stage.addEventListener('pointerup',endStageDrag);stage.addEventListener('pointercancel',endStageDrag);stageVideo.addEventListener('canplay',()=>{if(auto)stageVideo.play().catch(()=>{})});$('#spinToggle').onclick=e=>{auto=!auto;if(auto){stageVideo.play().catch(()=>{});e.target.textContent='Pause rotation'}else{stageVideo.pause();e.target.textContent='Resume rotation'}};
function openCart(){$('#cart').classList.add('open');$('#scrim').classList.add('show')}function closeCart(){$('#cart').classList.remove('open');$('#scrim').classList.remove('show')}$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#scrim').onclick=closeCart;
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><img src="${p.fallback||p.img}"><div><b>${p.name}</b><small>${money(p.price)}</small></div><button data-remove="${i}">×</button></div>`).join(''):'<p>Your bag is empty.</p>';$('#cartTotal').textContent=money(cart.reduce((s,p)=>s+p.price,0))}renderCart();
document.addEventListener('click',e=>{if(e.target.dataset.add){cart.push(products.find(p=>p.id==e.target.dataset.add));renderCart();openCart()}if(e.target.dataset.remove!==undefined){cart.splice(+e.target.dataset.remove,1);renderCart()}if(e.target.dataset.view){active=products.find(p=>p.id==e.target.dataset.view);$('#dialogImg').src=active.img;$('#dialogImg').onerror=()=>$('#dialogImg').src=active.fallback||'assets/casual-beige.jpg';$('#dialogName').textContent=active.name;$('#dialogDesc').textContent=active.desc;$('#dialogPrice').textContent=money(active.price);$('#dialogTag').textContent=active.tag;$('#dialogTag').className='badge '+active.status;$('#productDialog').showModal()}if(e.target.dataset.close)document.getElementById(e.target.dataset.close).close()});
$('#dialogAdd').onclick=()=>{cart.push(active);renderCart();$('#productDialog').close();openCart()};let d=false,dx=0,dr=0;$('#dialogViewer').onpointerdown=e=>{d=true;dx=e.clientX;$('#dialogViewer').setPointerCapture(e.pointerId)};$('#dialogViewer').onpointermove=e=>{if(!d)return;dr+=(e.clientX-dx)*.4;dx=e.clientX;$('#dialogImg').style.transform=`rotateY(${dr}deg) scale(${.95+Math.abs(Math.sin(dr*Math.PI/180))*.06})`};$('#dialogViewer').onpointerup=()=>d=false;
$('#checkoutBtn').onclick=()=>{if(!cart.length)return alert('Your bag is empty.');closeCart();$('#checkoutDialog').showModal()};$('#checkoutForm').onsubmit=e=>{e.preventDefault();$('#orderMessage').textContent='Order received. Connect a live gateway before production launch.';cart=[];renderCart();e.target.reset()};$('#newsletter').onsubmit=e=>{e.preventDefault();alert('Subscribed successfully.');e.target.reset()};$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');

const liquidCanvas=$('#liquidCanvas'),liquidCtx=liquidCanvas.getContext('2d');let liquidW=0,liquidH=0,pointerX=.72,pointerY=.45;function resizeLiquid(){const box=liquidCanvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,2);liquidW=box.width;liquidH=box.height;liquidCanvas.width=liquidW*ratio;liquidCanvas.height=liquidH*ratio;liquidCtx.setTransform(ratio,0,0,ratio,0,0)}resizeLiquid();addEventListener('resize',resizeLiquid);document.querySelector('.immersive').addEventListener('pointermove',e=>{const r=e.currentTarget.getBoundingClientRect();pointerX=(e.clientX-r.left)/r.width;pointerY=(e.clientY-r.top)/r.height});function liquidFrame(t){liquidCtx.clearRect(0,0,liquidW,liquidH);liquidCtx.globalCompositeOperation='lighter';const blobs=[{x:.72,y:.45,r:.32,s:.00045,c:'255,86,0'},{x:.87,y:.22,r:.22,s:.00062,c:'255,154,40'},{x:.60,y:.76,r:.26,s:.00053,c:'105,25,0'},{x:.94,y:.70,r:.19,s:.00075,c:'255,55,0'}];blobs.forEach((b,i)=>{const x=liquidW*(b.x+Math.sin(t*b.s+i)*.055+(pointerX-.5)*.025),y=liquidH*(b.y+Math.cos(t*b.s*.85+i)*.065+(pointerY-.5)*.025),r=Math.min(liquidW,liquidH)*b.r,g=liquidCtx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,`rgba(${b.c},.34)`);g.addColorStop(.45,`rgba(${b.c},.13)`);g.addColorStop(1,`rgba(${b.c},0)`);liquidCtx.fillStyle=g;liquidCtx.beginPath();liquidCtx.arc(x,y,r,0,Math.PI*2);liquidCtx.fill()});liquidCtx.globalCompositeOperation='source-over';requestAnimationFrame(liquidFrame)}requestAnimationFrame(liquidFrame);
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelectorAll('.product-card,.experience-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--rx',(-y*5)+'deg');card.style.setProperty('--ry',(x*7)+'deg')});card.addEventListener('pointerleave',()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg')})});const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.section-title,.editorial-copy,.about>div,.experience-card').forEach(el=>{el.classList.add('reveal');revealObserver.observe(el)})}
